services:
  - type: web
    name: tkd-car
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip cache purge
      pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PIP_NO_CACHE_DIR
        value: 1 